FROM alpine:3.19

RUN apk add --no-cache \
    build-base \
    git

RUN git clone https://github.com/catseye/Befunge-93.git /befunge

WORKDIR /befunge

RUN make

RUN cp bin/bef /usr/local/bin

RUN rm -rf /befunge

COPY . /app

WORKDIR /app

CMD ["bef", "app/main.bf"]
