jenkins:
  systemMessage: "Welcome to the Whanos jenkins."
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "admin"
         password: ${USER_ADMIN_PASSWORD}

jobs:
    - file: /usr/local/job_dsl.groovy

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false