- name: Update & Upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: "apt-transport-https"
    state: present
  become: true

- name: Install ca-certificates
  ansible.builtin.apt:
    name: "ca-certificates"
    state: present
  become: true

- name: Install git
  ansible.builtin.apt:
    name: "git"
    state: present
  become: true

- name: Install curl
  ansible.builtin.apt:
    name: "curl"
    state: present
  become: true

- name: install openjdk
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: fixed

- name: Set timezone to Europe/Paris
  community.general.timezone:
    name: Europe/Paris
  become: true

- name: Add GPG key for docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Make sure docker is started
  service:
    name: docker
    state: started
    enabled: yes
